#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

rm -rf log* processor* postProcessing
rm -rf *[1-9]*

#------------------------------------------------------------------------------
