#!/bin/sh

cd ${0%/*} || exit 1                        # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf log* processor* postProcessing

runApplication decomposePar -force
runParallel simpleFoam
runApplication reconstructPar

rm -rf processor*

runApplication postProcess -latestTime -fields '(phi p total(p))' -funcs '(inletAverage outletAverage outletFlow)'

pvpython post.py >> log.postProcess

#------------------------------------------------------------------------------
