#!/bin/sh
cd ${PBS_O_WORKDIR}

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf log* processor* postProcessing

runApplication decomposePar || exit 1
runParallel $(getApplication)
runApplication reconstructPar || exit 1

rm -rf processor*

#------------------------------------------------------------------------------
