#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory

[ ! -d results ] && \
	echo "Missing results directory!" && \
	exit 2
	

cd results
for resdir in man_??_*_results
do
		#get case name without _results
	name=`echo $resdir | sed 's/\(man_[0-9]*_[0-9]*\)_results/\1/'`
	echo
	echo "Results for case $name"
	
		#find lines with Pressure loss and get rid of some unnecessary chars
	grep 'Pressure loss' $resdir/log.postProcess | sed "s/[()\',]//g"
	
	grep 'Compression ratio' $resdir/log.postProcess | sed "s/[()\',]//g"
	
	grep 'Volume flow' "$resdir/log.postProcess" | sed "s/[()\',]//g"

	
		#last line from forces, get components in x and y, print them (and get rid of e+00 if it is there)
	tail -1 $resdir/force/0/force.dat | sed 's/^[[:digit:]]*\s*(\s*\(-\?[[:alnum:][:punct:]]\+\)\s*\(-\?[[:alnum:][:punct:]]\+\)\s*\(-\?[[:alnum:][:punct:]]\+\))\s*(.*)\s*(.*)\s*$/Force component in x: \1 \nForce component in y: \2/' | sed 's/e+00//g'
		
		#line that says if simulation converged
	grep 'solution converged in\s*[0-9]*\s*iterations' $resdir/log.simpleFoam
	[ "$?" -eq "1" ] && \
		echo "WARNING: Solution did not converge!"
done

exit 0

#------------------------------------------------------------------------------

